spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.csk.mall: debug