spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.csk.mall: debug